import type { CertQuestion } from "./cert-types";

// Scenario 4: Developer Productivity with Claude
export const DEVELOPER_PRODUCTIVITY_QUESTIONS: CertQuestion[] = [
	{
		id: "dp-q1",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "easy",
		stem: "You need to find all test files in a large React codebase that follow the naming pattern *.test.tsx or *.test.ts. The codebase has 500+ files across 30+ directories. What tool should the agent use?",
		choices: [
			{ key: "A", text: "Grep with pattern --include='*.test.*'" },
			{ key: "B", text: "Glob with pattern **/*.test.{ts,tsx}" },
			{ key: "C", text: "Read all files in src/ to identify test files" },
			{ key: "D", text: "Bash command find . -name '*.test.*'" },
		],
		correct: "B",
		explanation:
			"Glob is designed for file path pattern matching. **/*.test.{ts,tsx} directly matches the convention. Grep searches contents (slower); Read is overkill; Bash find is functional but not the primary Claude Code tool.",
		distractorRationales: {
			A: "Grep is for content search, not file path patterns.",
			C: "Bulk Read is wildly inefficient.",
			D: "Bash find works but isn't the canonical Claude Code tool for this.",
		},
		studyTags: ["Glob", "file-paths", "Task-2.5"],
	},
	{
		id: "dp-q2",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A file contains 12 lines with `const X = null;` and the agent needs to change only one specific line (line 42) to `const X = undefined;`. The anchor 'const X = null;' is not unique. What should the agent do?",
		choices: [
			{ key: "A", text: "Use Edit with anchor 'const X = null;' and hope it matches the right line." },
			{ key: "B", text: "Use Read, identify the specific line, use Edit with more unique surrounding text." },
			{ key: "C", text: "Use Bash sed to replace line 42." },
			{ key: "D", text: "Use Read, then Write to overwrite the entire file." },
		],
		correct: "B",
		explanation:
			"Task 2.5: when Edit's anchor isn't unique, Read first, then extend the anchor with surrounding context until it's unique. Edit with that anchor is surgical and correct.",
		distractorRationales: {
			A: "Edit with non-unique anchor will fail or edit the wrong line.",
			C: "Bash sed isn't the canonical Claude Code mechanism.",
			D: "Read + Write is the documented fallback only when no unique anchor can be found in context.",
		},
		studyTags: ["Edit", "anchor-uniqueness", "Task-2.5"],
	},
	{
		id: "dp-q3",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A team uses Jira for issue tracking and GitHub for repos. The Jira server is not yet officially supported; the team is evaluating a beta MCP implementation. Where should the Jira MCP be configured?",
		choices: [
			{ key: "A", text: ".mcp.json in the project root" },
			{ key: "B", text: "~/.claude.json in the user's home directory" },
			{ key: "C", text: "A shared CLAUDE.md file with MCP setup instructions" },
			{ key: "D", text: "A Git submodule with the MCP server code" },
		],
		correct: "B",
		explanation:
			"Beta/experimental servers go in user-level config. Move to .mcp.json once team-validated.",
		distractorRationales: {
			A: "Project config is for stable, team-adopted servers.",
			C: "CLAUDE.md is for code conventions, not MCP setup.",
			D: "Git submodule doesn't directly configure MCP.",
		},
		studyTags: ["mcp-config", "experimental", "Task-2.4"],
	},
	{
		id: "dp-q4",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "easy",
		stem: "A .mcp.json file needs to include a Jira API token. The team wants to ensure tokens are not stored in version control. Which is the correct pattern?",
		choices: [
			{ key: "A", text: "'JIRA_TOKEN': 'jira_token_abc123...'" },
			{ key: "B", text: "'JIRA_TOKEN': '${JIRA_TOKEN}'" },
			{ key: "C", text: "'JIRA_TOKEN': 'process.env.JIRA_TOKEN'" },
			{ key: "D", text: "'JIRA_TOKEN': '@env:JIRA_TOKEN'" },
		],
		correct: "B",
		explanation:
			".mcp.json supports ${ENV_VAR} expansion. Developers set 'export JIRA_TOKEN=...' in their shell.",
		distractorRationales: {
			A: "Hardcoded token, exposed in VCS.",
			C: "Not valid in JSON.",
			D: "Not the correct syntax.",
		},
		studyTags: ["env-var-expansion", "secrets", "Task-2.4"],
	},
	{
		id: "dp-q5",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A development team wants Claude Code to be aware of all available Jira projects (INFRA, FRONTEND, BACKEND, OPS) without making a tool call every time. What should the MCP server expose?",
		choices: [
			{ key: "A", text: "A tool list_projects that returns the list" },
			{ key: "B", text: "A resource jira://projects that returns ['INFRA', 'FRONTEND', 'BACKEND', 'OPS']" },
			{ key: "C", text: "A prompt hint that lists the projects" },
			{ key: "D", text: "A CLAUDE.md file with the project list" },
		],
		correct: "B",
		explanation:
			"Resources expose read-only data catalogs; agents can read them upfront without using a tool call each time. Tools are for actions or dynamic queries.",
		distractorRationales: {
			A: "Tool wastes a tool call for static data.",
			C: "Prompts are for system instructions, not data.",
			D: "CLAUDE.md is for code conventions, not external service data.",
		},
		studyTags: ["mcp-resources", "catalogs", "Task-2.4"],
	},
	{
		id: "dp-q6",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A team's MCP server includes a tool search_github_issues with description 'Search for issues.' The agent often ignores this tool and uses Grep instead. Most effective fix?",
		choices: [
			{ key: "A", text: "Disable Grep in the agent's tool list" },
			{ key: "B", text: "Add few-shot examples showing when to use the tool" },
			{ key: "C", text: "Expand the tool description to include input formats, output structure, and explicit 'Use this, not Grep, because...' guidance" },
			{ key: "D", text: "Rename the tool to find_github_issues_by_label" },
		],
		correct: "C",
		explanation:
			"Tool descriptions are the primary signal for tool selection. Expand with input/output specs and explicit alternatives.",
		distractorRationales: {
			A: "Disabling Grep removes a useful tool for code search.",
			B: "Few-shot helps; fixing the root cause (description) is more effective.",
			D: "Renaming alone doesn't clarify the distinction.",
		},
		studyTags: ["tool-descriptions", "Task-2.1"],
	},
	{
		id: "dp-q7",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "easy",
		stem: "A team uses both Jira and a proprietary issue tracker called 'InternalTrak.' Official MCP exists for Jira; no public MCP for InternalTrak. Which approach minimizes maintenance burden?",
		choices: [
			{ key: "A", text: "Build custom MCP servers for both" },
			{ key: "B", text: "Use the official Jira MCP server; build a custom MCP for InternalTrak" },
			{ key: "C", text: "Use Bash scripts for both" },
			{ key: "D", text: "Disable issue tracking integration" },
		],
		correct: "B",
		explanation:
			"Use community/official MCP servers for standard integrations to avoid maintenance. Reserve custom MCP for genuinely team-specific workflows.",
		distractorRationales: {
			A: "Building custom Jira MCP is unnecessary maintenance.",
			C: "Bash scripts are less integrated and don't expose tools.",
			D: "Removes valuable functionality.",
		},
		studyTags: ["community-mcp", "custom-mcp", "Task-2.4"],
	},
	{
		id: "dp-q8",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "An engineer asks: 'I need to understand how user authentication works in this codebase.' Most efficient exploration strategy?",
		choices: [
			{ key: "A", text: "Read all files in src/auth/ directory, then read all importing files" },
			{ key: "B", text: "Grep for authenticate/login/token patterns; Read entry point (e.g., src/auth/index.ts); identify exported functions; Grep each to find callers; Read only calling files" },
			{ key: "C", text: "Bash 'find src -name *.ts | head -20' and read them" },
			{ key: "D", text: "Spawn a subagent to 'understand authentication' and return a summary" },
		],
		correct: "B",
		explanation:
			"Incremental discovery (Grep → Read → Grep → Read) builds understanding efficiently. Bulk reads waste context; subagent hides details engineer needs.",
		distractorRationales: {
			A: "Bulk reading wastes context.",
			C: "Random sample misses relevant files.",
			D: "Subagents are for discovery isolation, not primary investigation when engineer wants detail.",
		},
		studyTags: ["incremental-discovery", "Grep-first", "Task-2.5"],
	},
	{
		id: "dp-q9",
		scenario: "developer-productivity",
		domain: "D3",
		tasks: ["1.7", "5.4"],
		mode: "canonical",
		difficulty: "hard",
		stem: "An engineer analyzed a codebase yesterday with claude --resume migration-analysis. Today, the team merged 15 commits affecting 8 files the engineer analyzed. How to continue?",
		choices: [
			{ key: "A", text: "Use claude --resume migration-analysis immediately" },
			{ key: "B", text: "Start a fresh session; pass a summary of yesterday's findings; inform Claude that specific files changed" },
			{ key: "C", text: "Use claude --resume but Grep changed files to re-validate prior analysis" },
			{ key: "D", text: "Fork the prior session" },
		],
		correct: "B",
		explanation:
			"Stale tool results are unreliable. New session + structured summary is safer than resuming with potentially outdated analysis.",
		distractorRationales: {
			A: "Resume includes stale tool results; prior analysis is now incorrect.",
			C: "Manual comparison is error-prone.",
			D: "Fork is for comparing approaches, not handling changed files.",
		},
		studyTags: ["session-resume", "stale-results", "Task-1.7"],
	},
	{
		id: "dp-q10",
		scenario: "developer-productivity",
		domain: "D3",
		tasks: ["3.4"],
		mode: "canonical",
		difficulty: "easy",
		stem: "Engineer provides a stack trace: 'Error at line 127 in utils/validate.ts: TypeError: expected string, got undefined.' The error is in a single function with a clear fix (null check). Plan mode or direct execution?",
		choices: [
			{ key: "A", text: "Plan mode to explore the codebase first" },
			{ key: "B", text: "Direct execution; the scope is clear" },
			{ key: "C", text: "Plan mode first, then direct execution" },
			{ key: "D", text: "Use an Explore subagent" },
		],
		correct: "B",
		explanation:
			"Direct execution for single-file, clear-scope, low-risk fixes.",
		distractorRationales: {
			A: "Overkill for a one-line fix.",
			C: "Combines both unnecessarily.",
			D: "Subagent exploration is unnecessary here.",
		},
		studyTags: ["direct-execution", "plan-mode", "Task-3.4"],
	},
	{
		id: "dp-q11",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "config.ts has these three lines: `export const LOG_LEVEL = 'info'; export const LOG_FORMAT = 'info'; export const LOG_HANDLER = 'file';`. The agent needs to change LOG_LEVEL to 'debug'. Anchor `= 'info';` appears twice. Correct approach?",
		choices: [
			{ key: "A", text: "Use Edit with anchor `const LOG_LEVEL = 'info';`" },
			{ key: "B", text: "Use Edit with anchor `export const LOG_LEVEL = 'info';`" },
			{ key: "C", text: "Use Read, then Write (overwrite entire file)" },
			{ key: "D", text: "Use Bash sed" },
		],
		correct: "A",
		explanation:
			"`const LOG_LEVEL = 'info';` is unique because the variable name disambiguates it. Minimal sufficient anchor is the canonical answer.",
		distractorRationales: {
			B: "Also unique but longer than necessary.",
			C: "Read + Write is the fallback when no unique anchor exists. Here, one does.",
			D: "Bash sed isn't the canonical Claude Code mechanism.",
		},
		studyTags: ["Edit", "anchor-extension", "Task-2.5"],
	},
	{
		id: "dp-q12",
		scenario: "developer-productivity",
		domain: "D1",
		tasks: ["1.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A coordinator agent discovers: 'Authentication is in src/auth/oauth.ts and src/auth/jwt.ts.' Coordinator spawns subagent: 'Find all places in the codebase that use authentication.' Subagent returns 'No authentication usage found.' Likely cause?",
		choices: [
			{ key: "A", text: "The codebase doesn't use authentication" },
			{ key: "B", text: "The subagent lacks context about the files where authentication is implemented" },
			{ key: "C", text: "Grep is disabled in the subagent" },
			{ key: "D", text: "The Explore subagent should have been used" },
		],
		correct: "B",
		explanation:
			"Subagent context is isolated. Coordinator must explicitly pass file locations: 'Authentication is in oauth.ts and jwt.ts. Find all callers.'",
		distractorRationales: {
			A: "Unlikely if coordinator already found it.",
			C: "Grep isn't typically disabled.",
			D: "Different subagent type wouldn't help; missing context is the issue.",
		},
		studyTags: ["subagent-isolation", "context-passing", "Task-1.3"],
	},
	{
		id: "dp-q13",
		scenario: "developer-productivity",
		domain: "D5",
		tasks: ["5.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "After 80 messages, engineer asks: 'Which database adapter is used in the ORM layer?' Claude responds: 'Based on the typical patterns, I believe it's likely either PostgreSQL or MySQL.' Most effective fix?",
		choices: [
			{ key: "A", text: "Grep for 'postgres' or 'mysql' to get the answer" },
			{ key: "B", text: "Start a new session with a summary of the 80-message exploration" },
			{ key: "C", text: "Run /compact to consolidate findings, then ask again" },
			{ key: "D", text: "Use a subagent to find the database adapter" },
		],
		correct: "C",
		explanation:
			"Vague 'typical patterns' phrasing is the textbook symptom of context degradation in extended sessions. /compact is the canonical first response.",
		distractorRationales: {
			A: "Targeted Grep finds the answer but doesn't address the degradation root cause.",
			B: "/compact preserves the structured summary while shedding verbose tool output.",
			D: "Subagents are for verbose discovery, not fixing main session degradation.",
		},
		studyTags: ["compact", "context-degradation", "Task-5.4"],
	},
	{
		id: "dp-q14",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A team has search_codebase (Grep wrapper, 50 files) and semantic_search (MCP, embeddings, 500 files with semantic understanding). Agent usually picks search_codebase even when semantic search would be more effective. Best first step?",
		choices: [
			{ key: "A", text: "Disable search_codebase" },
			{ key: "B", text: "Improve the semantic_search tool description to highlight semantic matching, vectorized search, broader scope, and explicit 'Use this for intent-based queries' guidance" },
			{ key: "C", text: "Add few-shot examples of when to use semantic_search" },
			{ key: "D", text: "Rename search_codebase to grep_wrapper" },
		],
		correct: "B",
		explanation:
			"Tool descriptions are the primary signal. Expand with semantics, scope, and differentiation.",
		distractorRationales: {
			A: "Disables a useful tool.",
			C: "Few-shot helps; fixing descriptions is more foundational.",
			D: "Renaming alone doesn't clarify purpose.",
		},
		studyTags: ["tool-descriptions", "differentiation", "Task-2.1"],
	},
	{
		id: "dp-q15",
		scenario: "developer-productivity",
		domain: "D3",
		tasks: ["3.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Project has instructions for test organization in .claude/CLAUDE.md at project root. New developer clones repo, opens in Claude Code, doesn't see test organization rules. Most likely cause?",
		choices: [
			{ key: "A", text: "Developer is using a personal CLAUDE.md that overrides the project-level one" },
			{ key: "B", text: "CLAUDE.md is not automatically loaded from project root; must be explicitly imported" },
			{ key: "C", text: "Developer hasn't set up shell environment correctly" },
			{ key: "D", text: "CLAUDE.md is ignored because it's in .claude/" },
		],
		correct: "A",
		explanation:
			"CLAUDE.md hierarchy: user → project → directory. User-level can take precedence and hide project rules.",
		distractorRationales: {
			B: ".claude/CLAUDE.md at project root IS automatically loaded.",
			C: "Shell env doesn't affect CLAUDE.md loading.",
			D: ".claude/ is the correct location for project-scoped config.",
		},
		studyTags: ["CLAUDE.md-hierarchy", "Task-3.1"],
	},
	{
		id: "dp-q16",
		scenario: "developer-productivity",
		domain: "D1",
		tasks: ["1.7"],
		mode: "canonical",
		difficulty: "medium",
		stem: "An engineer wants to test Strategy A (OAuth via external) vs Strategy B (custom JWT internal). Best way to compare?",
		choices: [
			{ key: "A", text: "Implement A, then manually implement B in a separate session" },
			{ key: "B", text: "Main agent analyzes the codebase, then spawns two fork sessions (or subagents): one to implement A, one to implement B. Compare results." },
			{ key: "C", text: "Implement both sequentially in the same session" },
			{ key: "D", text: "Use plan mode to design both approaches, then manually decide" },
		],
		correct: "B",
		explanation:
			"fork_session allows divergent exploration from a shared codebase baseline. Each fork independently implements and tests its strategy.",
		distractorRationales: {
			A: "Manual comparison is error-prone, context-heavy.",
			C: "Sequential in one session risks bias from first strategy.",
			D: "Plan mode is useful for design, but fork_session enables parallel implementation.",
		},
		studyTags: ["fork_session", "divergent-approaches", "Task-1.7"],
	},
	{
		id: "dp-q17",
		scenario: "developer-productivity",
		domain: "D5",
		tasks: ["5.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "After 60 messages exploring with 5+ bulk Reads of entire src/ contents, Claude responds vaguely: 'I believe it uses one of the common adapters like SQLAlchemy or Prisma, based on typical patterns.' Root cause and best mitigation?",
		choices: [
			{ key: "A", text: "Database adapter isn't in the codebase; Claude is guessing." },
			{ key: "B", text: "Context degradation from verbose Read outputs; specific details are lost. Mitigation: /compact or start fresh with a summary of prior findings." },
			{ key: "C", text: "Glob should have been used instead of Read." },
			{ key: "D", text: "Codebase uses multiple adapters and Claude is uncertain." },
		],
		correct: "B",
		explanation:
			"Vague language ('typical patterns') is the symptom of context degradation. Mitigate with /compact or fresh + summary.",
		distractorRationales: {
			A: "Specific details are in the codebase; the issue is degradation.",
			C: "Glob finds files; the issue is Read output accumulation.",
			D: "Multiple adapters might exist, but the symptom points to degradation.",
		},
		studyTags: ["context-degradation", "vague-language", "Task-5.4"],
	},
	// "Agentic AI Tools" deep-dive: designing tools (in custom MCP servers
	// or via the Tool Use API) that agents consume. Covers tool error
	// handling, retry boundaries, idempotency, input/output schema design,
	// pagination, scoped credentials, granularity, and resources vs tools.
	{
		id: "dp-q18",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.2", "5.3"],
		mode: "gotcha",
		difficulty: "hard",
		stem: "A custom MCP tool `fetch_invoice` already retries network timeouts 3 times internally with exponential backoff before giving up. When the internal retries are exhausted, what should the tool return so the agent doesn't immediately re-run the exact same retry loop?",
		choices: [
			{ key: "A", text: "Keep retrying inside the tool until it succeeds or the request is cancelled — agents are bad at retry timing and should not be trusted with it." },
			{ key: "B", text: "Return `{ isError: true, errorCategory: 'transient', isRetryable: false, description: 'Network timeout; 3 internal retries already attempted within this call. Retry only after a 30s cooldown or fall back to cached_invoice.' }`." },
			{ key: "C", text: "Return `{ isError: true, errorCategory: 'transient', isRetryable: true }` and let the agent decide whether to retry — the agent has more context." },
			{ key: "D", text: "Disable internal retries entirely; only the agent should ever retry, since the agent owns the conversation-level decision." },
		],
		correct: "B",
		explanation:
			"When the tool has already exhausted internal retries, signalling `isRetryable: true` causes the agent to do the same retry loop again — a double-retry. Set `isRetryable: false` and surface the next recovery step (cooldown window, fallback tool).",
		distractorRationales: {
			A: "Unbounded internal retry blocks the agent and hides the failure; the agent can never escalate or fall back.",
			C: "Reports the failure as retryable when the tool just exhausted its retries — guarantees a wasted second attempt.",
			D: "Removes the cheap, low-latency retry for jitter that the tool is best positioned to handle.",
		},
		studyTags: ["double-retry", "isRetryable", "tool-vs-agent-retry", "Task-2.2", "Task-5.3"],
	},
	{
		id: "dp-q19",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A custom MCP tool wraps a flaky third-party API. The API returns three error classes: network timeouts / 5xx (intermittent), 403 (insufficient OAuth scope), and 422 (input failed server-side validation). Which classes should the tool retry internally, and which should it surface immediately?",
		choices: [
			{ key: "A", text: "Tools should never retry; the agent owns all retry logic so timing is consistent across every tool in the system." },
			{ key: "B", text: "The agent should never retry; the tool is closer to the error and owns all retry semantics for its underlying API." },
			{ key: "C", text: "Retry low-level transient failures the tool owns (network jitter, 5xx). Surface 403 and 422 immediately as structured non-retryable errors — a scope grant or input change is required and only the agent or upstream policy can decide." },
			{ key: "D", text: "Retry every error class (timeouts, 403, 422) — a 403 might clear after a token refresh and a 422 might pass once upstream state changes, so retries are always worth attempting." },
		],
		correct: "C",
		explanation:
			"Split retry responsibility by who can fix the failure. Transient infra errors stay in the tool. Errors that require a different decision (auth, validation, business rules) surface immediately so the agent or user can act.",
		distractorRationales: {
			A: "Forces every agent to re-implement transient retry; loses the low-latency local retry the tool is best positioned to do.",
			B: "Hides the failure category from the agent and prevents conversation-level recovery (escalation, alternate tool).",
			D: "Blindly retrying 403/422 burns latency and quota on errors that won't fix themselves.",
		},
		studyTags: ["retry-boundary", "error-categories", "transient-vs-validation", "Task-2.2"],
	},
	{
		id: "dp-q20",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.2"],
		mode: "trick",
		difficulty: "medium",
		stem: "A `send_email` MCP tool occasionally times out *after* dispatching the email but before returning a response. When the agent retries the call, the customer receives two identical emails. What is the best design fix?",
		choices: [
			{ key: "A", text: "Accept an `idempotency_key` parameter; on receiving a duplicate key within the dedup window the tool returns the cached prior result without re-sending the email." },
			{ key: "B", text: "Mark `send_email` as `isRetryable: false` so agents never retry mutating tools, regardless of the underlying failure category." },
			{ key: "C", text: "Catch every tool-call timeout in the agent's wrapper layer and refuse to retry any mutating tool ever — read-only tools only." },
			{ key: "D", text: "Wrap each call in a database transaction with SERIALIZABLE isolation so the second retry blocks until the first commits and only one actually runs." },
		],
		correct: "A",
		explanation:
			"Idempotency keys let the agent retry safely. The tool dedupes server-side using the key the caller already sent. This is the canonical pattern for mutating tools (Stripe, SQS, etc.).",
		distractorRationales: {
			B: "Blanket non-retryable breaks legitimate retries on genuine network failures; the underlying duplicate-side-effect problem is unsolved.",
			C: "Pushes the workaround into the agent harness and disables an important capability; doesn't fix the underlying API.",
			D: "DB transactions can't prevent duplicate emails — the email is dispatched to an external SMTP server outside the transaction boundary.",
		},
		studyTags: ["idempotency-key", "mutation-safety", "Task-2.2"],
	},
	{
		id: "dp-q21",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1", "2.2"],
		mode: "gotcha",
		difficulty: "medium",
		stem: "A `query_database` MCP tool accepts a freeform `query` string and runs it against the analytics DB. Agents occasionally generate SQL containing `DROP TABLE` or `DELETE FROM`. Most reliable fix?",
		choices: [
			{ key: "A", text: "Add to the tool description: 'Do not use DROP or DELETE — read-only queries only.' Trust the model to honor the constraint." },
			{ key: "B", text: "Wire a permission hook to prompt the human user before every `query_database` call, so the user can reject destructive SQL." },
			{ key: "C", text: "Rename the tool to `read_database`, rely on the model honoring the name, and add a few-shot example showing a safe SELECT pattern." },
			{ key: "D", text: "Replace the freeform `query` parameter with structured parameters (`table`, `columns`, `where`, `limit`). The tool builds the read-only SELECT internally; arbitrary SQL is no longer accepted." },
		],
		correct: "D",
		explanation:
			"Constrain the API surface. A tool's input schema is a hard contract — agents can't generate inputs the schema doesn't allow. Prompt-based or naming-based mitigations stay probabilistic.",
		distractorRationales: {
			A: "Description text is a probabilistic signal; agents will violate it some percentage of the time, especially under unusual prompts.",
			B: "Permission prompts interrupt the workflow on every call and don't address the root cause (the unsafe surface area).",
			C: "Renaming alone doesn't change the contract; the tool still accepts and executes arbitrary SQL.",
		},
		studyTags: ["input-schema", "safe-by-construction", "Task-2.1", "Task-2.2"],
	},
	{
		id: "dp-q22",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A `list_files` MCP tool returns 2000 file paths in a single 80KB string. The agent often misattributes paths or hallucinates entries that don't exist. What's the best change to the tool's output design?",
		choices: [
			{ key: "A", text: "Truncate the response to the first 100 entries — agents can't reason about 2000 items in a single context window anyway, and pagination just adds complexity." },
			{ key: "B", text: "Return paginated results with a cursor: `{ items, nextCursor, totalCount }`. Document the pagination protocol in the tool description so the agent can iterate when it needs more." },
			{ key: "C", text: "Compress the response with gzip and return it base64-encoded so it consumes fewer characters in the context window." },
			{ key: "D", text: "Return only the total count; instruct the agent (via description) to call a separate `filter_files` tool to drill down without ever materializing the full list." },
		],
		correct: "B",
		explanation:
			"Pagination is the canonical pattern for large list responses. It bounds per-call token cost while still letting the agent see everything it needs.",
		distractorRationales: {
			A: "Silently drops 1900 files; the agent can't know what was excluded.",
			C: "Tokenization counts characters, not compressed bytes — base64 of gzip is usually larger token-wise than the original list.",
			D: "Forces a two-tool workflow even when the agent legitimately needs the full list.",
		},
		studyTags: ["pagination", "result-size", "Task-2.1"],
	},
	{
		id: "dp-q23",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.3"],
		mode: "canonical",
		difficulty: "hard",
		stem: "An MCP `update_user_profile` tool is shared between a customer-support agent (should only update the calling user's own record) and an internal admin agent (can update any user). How should the tool enforce this distinction?",
		choices: [
			{ key: "A", text: "Add to the tool description 'Admin-only on cross-user updates' and trust each agent's system prompt to honor the constraint." },
			{ key: "B", text: "Have the calling agent pass `is_admin: true` as a parameter so the tool can branch on the flag for the cross-user code path." },
			{ key: "C", text: "The MCP server receives the caller's scoped credential (e.g., OAuth access token with role claims) at session start; the tool checks the role server-side and rejects out-of-scope updates with `errorCategory: 'permission', isRetryable: false`." },
			{ key: "D", text: "Run two separate MCP server processes — one wired to support-agent sessions with no cross-user surface, one wired to admin sessions with the full surface — so the agent type never sees the wrong tool." },
		],
		correct: "C",
		explanation:
			"Authorization belongs server-side, keyed on a credential the agent cannot forge. Returning a structured `permission` error gives the agent a clean recovery path (escalate, prompt user) without ever leaking unauthorized writes.",
		distractorRationales: {
			A: "Trust-based enforcement; one prompt-injection or model error and the constraint is gone.",
			B: "An agent-supplied flag is unauthenticated — any prompt-injected input could set it to true.",
			D: "Two-process isolation works but is heavyweight and brittle; in-server role checks generalize better and stay correct as roles evolve.",
		},
		studyTags: ["scoped-credentials", "authorization", "permission-error", "Task-2.3"],
	},
	{
		id: "dp-q24",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1", "2.3"],
		mode: "trick",
		difficulty: "medium",
		stem: "A support team has three MCP tools: `get_user`, `get_user_orders`, `get_user_payments`. Most tickets need all three, so agents make 3 sequential calls per ticket. A proposal: consolidate them into a single `get_customer_360(user_id)` tool. Best approach?",
		choices: [
			{ key: "A", text: "Yes — collapse all three into `get_customer_360`. Fewer calls is always faster and the agent doesn't need to choose granularity." },
			{ key: "B", text: "No — keep them strictly separate. Aggregation hides what data the agent actually needs and increases the blast radius of a buggy query that breaks all three lookups at once." },
			{ key: "C", text: "Run all three in parallel via a meta-tool every time; the agent can ignore fields it doesn't need." },
			{ key: "D", text: "Add a `get_customer_360` aggregate alongside the existing focused tools; the agent picks granularity based on need. Update descriptions so it's clear when to use the aggregate vs the focused tools." },
		],
		correct: "D",
		explanation:
			"Don't choose between split or aggregate — offer both, with clear descriptions. Agents pick the aggregate for the common path and the focused tools when they only need one slice. Avoids the latency tax without losing precision.",
		distractorRationales: {
			A: "Forces a heavy call even when the agent only needs the customer's email.",
			B: "Leaves the 3x-latency tax on the common path despite a clear win available.",
			C: "Always materializing everything wastes tokens; the agent often only needs orders, not payments.",
		},
		studyTags: ["tool-granularity", "aggregate-vs-focused", "Task-2.1", "Task-2.3"],
	},
	{
		id: "dp-q25",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.2", "5.3"],
		mode: "canonical",
		difficulty: "easy",
		stem: "You're defining the error vocabulary for a new internal MCP server. Which categorization gives the agent the most useful information for choosing recovery?",
		choices: [
			{ key: "A", text: "A single `error` category with a freeform `description` field. The agent reads the description text and decides what to do, which keeps the schema flexible across all tools." },
			{ key: "B", text: "`transient | validation | permission | business`, plus an `isRetryable` boolean — so the agent can route between retry, fix input, escalate, or surface to the user." },
			{ key: "C", text: "Raw HTTP status codes (`500`, `403`, `422`) lifted from the underlying API so the agent has the most precise signal possible." },
			{ key: "D", text: "Two categories: `recoverable` and `unrecoverable` — anything more granular is over-engineering." },
		],
		correct: "B",
		explanation:
			"Task 2.2's standard category set maps directly to distinct recovery branches. `isRetryable` separates the retry decision from the category so the agent has clean conditional logic.",
		distractorRationales: {
			A: "Forces the agent to parse free text to decide recovery — fragile and inconsistent across tools.",
			C: "HTTP codes leak transport details and don't map 1:1 to recovery (a 422 could be validation OR business).",
			D: "Collapses permission and business errors into the same bucket, so the agent can't tell 'escalate' from 'show the user the validation hint'.",
		},
		studyTags: ["error-vocabulary", "errorCategory", "Task-2.2", "Task-5.3"],
	},
	{
		id: "dp-q26",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You're designing an MCP integration with an internal CRM. The CRM has both fairly static data (pipeline stage list, account hierarchy, user directory) and dynamic actions (create deal, log call, update opportunity). How should you split exposure across MCP resources and tools?",
		choices: [
			{ key: "A", text: "Expose static catalogs (stage list, user directory) as resources so agents can read them once per session; expose state-changing actions and per-request dynamic queries as tools." },
			{ key: "B", text: "Expose everything as tools. MCP resources duplicate functionality and add a concept the agent has to track on top of tools." },
			{ key: "C", text: "Expose everything as resources — tools spend a tool call every time and resources are read once per session, which is strictly cheaper." },
			{ key: "D", text: "Use prompts for actions, resources for queries, and reserve tools for OAuth callbacks and webhook delivery only." },
		],
		correct: "A",
		explanation:
			"Resources for read-only catalogs the agent benefits from seeing upfront. Tools for actions and dynamic queries. This is the canonical MCP split.",
		distractorRationales: {
			B: "Wastes a tool call per session on data that never changes.",
			C: "Resources can't take parameters or cause side effects — actions and dynamic queries have to be tools.",
			D: "Prompts are for system-level instructions, not actions. Misuses every primitive.",
		},
		studyTags: ["mcp-resources-vs-tools", "Task-2.4"],
	},
	{
		id: "dp-q27",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A `process_refund` MCP tool receives a request for a $5000 refund. Company policy caps automated refunds at $500. What should the tool return?",
		choices: [
			{ key: "A", text: "Process the refund anyway and log a warning to the audit trail so the team can review it after the fact." },
			{ key: "B", text: "Silently cap the refund at $500 and return success — the customer still gets a refund and the agent doesn't have to handle a second decision branch." },
			{ key: "C", text: "Return `{ isError: true, errorCategory: 'business', isRetryable: false, description: 'Refund $5000 exceeds automated cap of $500. Escalate to a human approver, or split into multiple sub-cap refunds.' }`." },
			{ key: "D", text: "Throw a generic exception and let the agent infer from the message that it should retry with a smaller amount." },
		],
		correct: "C",
		explanation:
			"Business-rule violations are a distinct category from validation or transient failures. The structured `business` error gives the agent a clean path: escalate or restructure the request. Silent capping or auto-approving hides policy from the audit trail.",
		distractorRationales: {
			A: "Violates the policy the tool exists to enforce; the warning is after-the-fact and the money is already gone.",
			B: "Silent partial-success creates customer-facing inconsistency and audit gaps; the agent never learns about the cap.",
			D: "Generic exceptions force the agent to guess; the next call is likely to repeat the same mistake.",
		},
		studyTags: ["business-error", "policy-enforcement", "Task-2.2"],
	},
];
